### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by kant2002** [JetBrains/resharper-fsharp#447]
After I update to latest version, after my experiments with #445 I observe following
- I can run plugin inside IDE
- but I cannot run tests inside Idea.
```
./gradew test 
```
produces for example
```
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':detachedConfiguration12'.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1524)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3700(DefaultConfiguration.java:159)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.rethrowFailure(DefaultConfiguration.java:2174)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1496)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:510)
        at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:129)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromMultipleRepositories(DependenciesDownloader.kt:70)
        at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromRepository(DependenciesDownloader.kt:33)
        at org.jetbrains.intellij.utils.DependenciesDownloader.downloadFromRepository$default(DependenciesDownloader.kt:32)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveSources(IdeaDependencyManager.kt:123)
        at org.jetbrains.intellij.dependency.IdeaDependencyManager.resolveRemote(IdeaDependencyManager.kt:363)
        at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1$1.call(IntelliJPlugin.kt:1524)
        at org.jetbrains.intellij.IntelliJPlugin$configureSetupDependenciesTask$1$1.call(IntelliJPlugin.kt:114)
```

and tests seems to be does not run. Not sure what to do.

**Comment by kant2002** [comment]
Side node. I mostly C# developer by trade, and I would appreciate that process of running tests for Java would be documented. Probably the same for C# part, since if Java develop decides to contribute it may suffer same problem as me.

**Comment by auduchinok** [comment]
This is a recent issue, and should be fixed in either [`gradle-intellij`](https://github.com/JetBrains/gradle-intellij-plugin) or in the Rider SDK. I've reported it internally and will post a workaround if one is found before the fix.

Just a side note: the most of the tests are written in the .NET part of the plugin, and Java part contains only a few of them, mostly integration ones. For the most of the time you're probably interested in running tests in the ReSharper.FSharp solution instead.

**Comment by kant2002** [comment]
My experiment consist of implementing custom keywords for F#, so I would like to run everything I have. Also I would be happy to know what’s canonical way to run tests, so I at least can improve docs in this area

**Comment by auduchinok** [comment]
This has been fixed.
